version: '3'
services:
  app:
    image: tarlub/converter:latest
    command: bundle exec ruby app.rb -s Puma
    ports:
      - 4567:4567
    depends_on:
      - mongodb  
    links:
      - redis
      - mongodb
    env_file:
      - .env
    tty: true
    stdin_open: true
  sidekiq:
    image: tarlub/converter:latest
    env_file:
      - .env
    links:
      - mongodb
      - redis
    command: bundle exec sidekiq -r ./app.rb
  redis:
    image: redis:latest
  mongodb:
    image: mongo


    