source 'https://rubygems.org'
ruby '2.7.0'

gem 'activesupport'
gem 'concurrent-ruby'
gem 'faraday'
gem 'haml'
gem 'interactor', '~> 3.0'
gem 'mongoid', '7.2'
gem 'pry'
gem 'puma'
gem 'rack'
gem 'redis'
gem 'sidekiq'
gem 'sidekiq-cron', '~> 1.1'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'therubyracer'
